package com.geoplano.game;

import android.app.Activity;
import android.os.Bundle;
import android.webkit.WebChromeClient;
import android.webkit.WebSettings;
import android.webkit.WebView;
import android.webkit.WebViewClient;

public class MainActivity extends Activity {
  @Override public void onCreate(Bundle b){
    super.onCreate(b);
    WebView w=new WebView(this); setContentView(w);
    WebSettings s=w.getSettings(); s.setJavaScriptEnabled(true); s.setDomStorageEnabled(true);
    w.setWebViewClient(new WebViewClient()); w.setWebChromeClient(new WebChromeClient());
    String h="""
<!doctype html><html><head><meta name='viewport' content='width=device-width,initial-scale=1,maximum-scale=1'><style>
*{box-sizing:border-box}body{margin:0;font-family:Arial;background:linear-gradient(#123d76,#061528);color:white}.app{max-width:900px;margin:auto;padding:14px}h1{color:#ffd83b;text-shadow:0 2px #9f5c00}.card{background:#0d2c55;border:1px solid #3971ad;border-radius:18px;padding:14px;margin:10px 0}.btn{width:100%;padding:14px;margin:6px 0;border:0;border-radius:13px;font-weight:bold;font-size:16px;color:white}.g{background:#20c764}.b{background:#1688ed}.p{background:#8a43e8}.o{background:#ef8a19}.y{background:#d7a90b}.row{display:flex;gap:8px}.row>*{flex:1}.hide{display:none}canvas{width:100%;aspect-ratio:1;background:#d79a55;border:6px solid #78451e;border-radius:16px;touch-action:none}.avatar{font-size:64px;text-align:center}.small{color:#bed6f2}.code{font-size:28px;letter-spacing:4px;text-align:center;font-weight:bold}.top{display:flex;justify-content:space-between;align-items:center}select,input{width:100%;padding:12px;border-radius:10px;border:1px solid #4278af;background:#071a34;color:#fff}
</style></head><body><div class='app'><div class='top'><h1>GEOPLANO</h1><b>⭐ <span id='pts'>0</span></b></div>
<div id='home'><div class='card'><div class='avatar' id='av'>🧑🏻‍🎤</div><h2 id='nm'>Jogador</h2><p class='small'>Forme figuras, avance de nível e dispute pontos.</p><button class='btn g' onclick="show('game')">▶ JOGAR</button><button class='btn b' onclick="show('profile')">🧢 AVATAR</button><button class='btn p' onclick="show('multi')">👥 MULTIPLAYER</button><button class='btn o' onclick="show('rank')">🏆 RANKING</button></div></div>
<div id='profile' class='hide'><button class='btn b' onclick="show('home')">← VOLTAR</button><div class='card'><h2>Meu perfil</h2><input id='name' placeholder='Seu nome'><div class='row'><button class='btn p' onclick="pick('🧑🏻‍🎤')">🧑🏻‍🎤</button><button class='btn p' onclick="pick('🦸🏽')">🦸🏽</button><button class='btn p' onclick="pick('🥷🏽')">🥷🏽</button><button class='btn p' onclick="pick('🧙🏻')">🧙🏻</button></div><button class='btn g' onclick='saveProfile()'>SALVAR</button></div></div>
<div id='multi' class='hide'><button class='btn b' onclick="show('home')">← VOLTAR</button><div class='card'><h2>Sala multiplayer</h2><button class='btn g' onclick='createRoom()'>CRIAR SALA</button><div class='code' id='room'>------</div><input id='join' maxlength='6' placeholder='Código da sala'><button class='btn p' onclick='joinRoom()'>ENTRAR NA SALA</button><p class='small'>O código de convite já funciona. A sincronização online entre dois celulares será ativada quando o servidor da sala estiver publicado.</p></div></div>
<div id='rank' class='hide'><button class='btn b' onclick="show('home')">← VOLTAR</button><div class='card'><h2>🏆 Ranking</h2><div id='ranking'></div></div></div>
<div id='game' class='hide'><button class='btn b' onclick="show('home')">← SAIR</button><div class='card'><div class='row'><select id='mode' onchange='newRound()'><option value='3'>Triângulos</option><option value='4'>Quadrados</option><option value='5'>Pentágonos</option><option value='6'>Hexágonos</option><option value='0'>Livre</option></select><select id='grid' onchange='newRound()'><option>3</option><option>4</option><option selected>5</option><option>6</option><option>8</option><option>10</option><option>12</option></select></div><p id='goal'></p><canvas id='c' width='700' height='700'></canvas><div class='row'><button class='btn o' onclick='undo()'>↶ DESFAZER</button><button class='btn y' onclick='clearB()'>LIMPAR</button></div><button class='btn g' onclick='finish()'>✓ FINALIZAR FIGURA</button><h3>Nível <span id='level'>1</span></h3></div></div>
</div><script>
let st=JSON.parse(localStorage.gp||'null')||{name:'Jogador',avatar:'🧑🏻‍🎤',pts:0,level:1};let path=[];let cv=document.getElementById('c'),x=cv.getContext('2d');function save(){localStorage.gp=JSON.stringify(st);pts.textContent=st.pts;nm.textContent=st.name;av.textContent=st.avatar}function show(id){['home','profile','multi','rank','game'].forEach(z=>document.getElementById(z).classList.toggle('hide',z!==id));if(id==='rank')renderRank();if(id==='game')newRound()}function pick(a){st.avatar=a;save()}function saveProfile(){st.name=(name.value||'Jogador').trim();save();show('home')}function createRoom(){let a='ABCDEFGHJKLMNPQRSTUVWXYZ23456789',s='';for(let i=0;i<6;i++)s+=a[Math.floor(Math.random()*a.length)];room.textContent=s}function joinRoom(){alert(join.value.length===6?'Sala '+join.value.toUpperCase()+' preparada':'Digite um código de 6 caracteres')}function renderRank(){ranking.innerHTML='<p>1º 🦸🏽 GeoMax — 12450 pts</p><p>2º 🧙🏻 FormaPro — 10900 pts</p><p>3º '+st.avatar+' '+st.name+' — '+st.pts+' pts</p>'}function ptsArr(){let n=+grid.value,m=55,s=(700-2*m)/(n-1),a=[];for(let j=0;j<n;j++)for(let i=0;i<n;i++)a.push({x:m+i*s,y:m+j*s});return a}function draw(){x.fillStyle='#d59a58';x.fillRect(0,0,700,700);let a=ptsArr();if(path.length){x.strokeStyle='#22d46c';x.lineWidth=10;x.lineJoin='round';x.beginPath();path.forEach((q,i)=>{let p=a[q];i?x.lineTo(p.x,p.y):x.moveTo(p.x,p.y)});x.stroke()}a.forEach(p=>{x.beginPath();x.arc(p.x,p.y,8,0,Math.PI*2);x.fillStyle='white';x.fill();x.stroke()})}cv.onpointerdown=e=>{let r=cv.getBoundingClientRect(),px=(e.clientX-r.left)*700/r.width,py=(e.clientY-r.top)*700/r.height,a=ptsArr(),best=-1,bd=35;a.forEach((p,i)=>{let d=Math.hypot(p.x-px,p.y-py);if(d<bd){bd=d;best=i}});if(best<0)return;if(path.length>1&&best===path[0])path.push(best);else if(!path.includes(best))path.push(best);draw()};function undo(){path.pop();draw()}function clearB(){path=[];draw()}function newRound(){path=[];let m=+mode.value;goal.textContent=m?('Feche uma figura com '+m+' lados.'):'Crie qualquer forma fechada.';level.textContent=st.level;draw()}function finish(){let closed=path.length>=4&&path[0]===path[path.length-1],sides=closed?path.length-1:path.length,t=+mode.value;if(!closed||sides<3||(t&&sides!==t)){alert('A figura ainda não corresponde ao desafio.');return}let add=100+st.level*15;st.pts+=add;st.level++;save();alert('Perfeito! +'+add+' pontos');newRound()}save();draw();
</script></body></html>
""";
    w.loadDataWithBaseURL(null,h,"text/html","UTF-8",null);
  }
}
