(()=>{
'use strict';
const qs=s=>document.querySelector(s),qsa=s=>[...document.querySelectorAll(s)];
let drag=null,ghost=null,suppressClickUntil=0,lastRackIds=[],toastTimer=null;
let customOrder=JSON.parse(localStorage.rumixV05RackOrder||'[]');
function toast(msg){let el=qs('#v05Toast');if(!el){el=document.createElement('div');el.id='v05Toast';document.body.appendChild(el)}el.textContent=msg;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),1400)}
function ensureUi(){if(!qs('#v05DropTarget')){const d=document.createElement('div');d.id='v05DropTarget';d.textContent='SOLTE NA MESA';document.body.appendChild(d)}if(!qs('#v05Stage')){const s=document.createElement('div');s.id='v05Stage';s.innerHTML='<span class="stage-label">Peças preparadas</span><div id="v05StageTiles"></div><button id="v05StagePlay">JOGAR</button>';document.body.appendChild(s);qs('#v05StagePlay').onclick=()=>{const b=qs('#playBtn');if(b&&!b.disabled){b.click();toast('Combinação enviada para a mesa')}else toast('Aguarde a sua vez')}}const sv=qs('#sortValueBtn'),sc=qs('#sortColorBtn');if(sv&&!sv.dataset.v05){sv.dataset.v05='1';sv.addEventListener('click',()=>{customOrder=[];saveOrder()})}if(sc&&!sc.dataset.v05){sc.dataset.v05='1';sc.addEventListener('click',()=>{customOrder=[];saveOrder()})}}
function saveOrder(){localStorage.rumixV05RackOrder=JSON.stringify(customOrder)}
function tileClone(el){const c=el.cloneNode(true);c.classList.remove('selected','v05-dragging');c.removeAttribute('data-v05');return c}
function selectedEls(){return qsa('#rack .tile.selected,#editPool .tile.selected')}
function updateStage(){ensureUi();const stage=qs('#v05Stage'),box=qs('#v05StageTiles'),sel=selectedEls();if(!stage||!box)return;box.innerHTML='';sel.forEach(el=>box.appendChild(tileClone(el)));stage.classList.toggle('active',sel.length>0);const play=qs('#v05StagePlay');if(play){play.disabled=sel.length<3;play.textContent=sel.length>=3?'JOGAR':'+'+(3-sel.length)}}
function applyRackOrder(){const rack=qs('#rack');if(!rack)return;const els=qsa('#rack .tile'),ids=els.map(e=>e.dataset.id);if(ids.join('|')!==lastRackIds.join('|')){lastRackIds=ids.slice();customOrder=customOrder.filter(id=>ids.includes(id));ids.forEach(id=>{if(!customOrder.includes(id))customOrder.push(id)});saveOrder()}els.forEach(el=>{const i=customOrder.indexOf(el.dataset.id);el.style.order=i<0?999:i})}
function annotateButtons(){const labels={sortValueBtn:'Ordenar números',sortColorBtn:'Ordenar cores',hintBtn:'Dica',resetTurnBtn:'Restaurar turno',newTrainingBtn:'Nova mão',clearTrainingBtn:'Limpar mesa'};Object.entries(labels).forEach(([id,label])=>{const e=qs('#'+id);if(e){e.title=label;e.setAttribute('aria-label',label)}})}
function pointIn(el,x,y){if(!el)return false;const r=el.getBoundingClientRect();return x>=r.left&&x<=r.right&&y>=r.top&&y<=r.bottom}
function startDrag(ev,el){if(ev.button!==undefined&&ev.button!==0)return;drag={id:el.dataset.id,el,startX:ev.clientX,startY:ev.clientY,x:ev.clientX,y:ev.clientY,moved:false,fromRack:!!el.closest('#rack')};try{el.setPointerCapture(ev.pointerId)}catch(e){}}
function makeGhost(el,x,y){ghost=tileClone(el);ghost.classList.add('v05-ghost');document.body.appendChild(ghost);moveGhost(x,y);el.classList.add('v05-dragging');document.body.classList.add('v05-drag-active')}
function moveGhost(x,y){if(ghost){ghost.style.left=x+'px';ghost.style.top=y+'px'}}
function moveDrag(ev){if(!drag)return;drag.x=ev.clientX;drag.y=ev.clientY;const dist=Math.hypot(ev.clientX-drag.startX,ev.clientY-drag.startY);if(!drag.moved&&dist>8){drag.moved=true;makeGhost(drag.el,ev.clientX,ev.clientY)}if(!drag.moved)return;ev.preventDefault();moveGhost(ev.clientX,ev.clientY);document.body.classList.toggle('v05-over-board',pointIn(qs('#table'),ev.clientX,ev.clientY))}
function reorderRack(id,x){const els=qsa('#rack .tile').filter(e=>e.dataset.id!==id);if(!els.length)return;let target=els.find(e=>{const r=e.getBoundingClientRect();return x<r.left+r.width/2})||els[els.length-1];customOrder=customOrder.filter(v=>v!==id);let idx=customOrder.indexOf(target.dataset.id);if(idx<0)idx=customOrder.length;const tr=target.getBoundingClientRect();if(x>tr.left+tr.width/2)idx++;customOrder.splice(Math.min(idx,customOrder.length),0,id);saveOrder();applyRackOrder();toast('Rack reorganizado')}
function dropDrag(ev){if(!drag)return;const d=drag;drag=null;if(d.moved){suppressClickUntil=Date.now()+320;ev.preventDefault();const overBoard=pointIn(qs('#table'),ev.clientX,ev.clientY),overRack=pointIn(qs('#rack'),ev.clientX,ev.clientY);if(overBoard){const current=qsa('#rack .tile,#editPool .tile').find(e=>e.dataset.id===d.id);if(current&&!current.classList.contains('selected'))current.click();toast('Peça preparada na mesa')}else if(overRack&&d.fromRack)reorderRack(d.id,ev.clientX)}qsa('.v05-dragging').forEach(e=>e.classList.remove('v05-dragging'));if(ghost){ghost.remove();ghost=null}document.body.classList.remove('v05-drag-active','v05-over-board');setTimeout(updateStage,20)}
function bindTile(el){if(el.dataset.v05)return;el.dataset.v05='1';el.addEventListener('pointerdown',ev=>startDrag(ev,el),{passive:true});el.addEventListener('pointermove',moveDrag,{passive:false});el.addEventListener('pointerup',dropDrag,{passive:false});el.addEventListener('pointercancel',dropDrag,{passive:false});el.addEventListener('click',ev=>{if(Date.now()<suppressClickUntil){ev.preventDefault();ev.stopImmediatePropagation()}},true)}
function bindGroups(){qsa('#table .group').forEach(g=>{if(g.dataset.v05)return;g.dataset.v05='1';let t=null,sx=0,sy=0;g.addEventListener('pointerdown',ev=>{if(ev.target.closest('.tile'))return;sx=ev.clientX;sy=ev.clientY;t=setTimeout(()=>{const b=g.querySelector('[data-edit-group]');if(b){b.click();toast('Grupo liberado para reorganização')}},520)});g.addEventListener('pointermove',ev=>{if(Math.hypot(ev.clientX-sx,ev.clientY-sy)>8)clearTimeout(t)});['pointerup','pointercancel','pointerleave'].forEach(n=>g.addEventListener(n,()=>clearTimeout(t)))})}
function refresh(){ensureUi();annotateButtons();qsa('#rack .tile,#editPool .tile').forEach(bindTile);bindGroups();applyRackOrder();updateStage();if(!localStorage.rumixHints){localStorage.rumixHints='off';const s=qs('#hintsSetting');if(s)s.value='off';const b=qs('#hintBtn');if(b)b.classList.add('hide')}}
const obs=new MutationObserver(()=>requestAnimationFrame(refresh));
function boot(){ensureUi();const game=qs('#game');if(game)obs.observe(game,{childList:true,subtree:true});refresh();toast('Nova mesa: arraste peças para jogar')}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
