(()=>{
'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const MODES={classic:'Números Clássico',words:'Letras & Palavras',mixed:'Misto Letras + Números'},COLORS=['red','blue','green','orange'],ABC='ABCDEFGHIJKLMNOPQRSTUVWXYZ'.split('');
const id=localStorage.rumixClientId||(localStorage.rumixClientId='p-'+rnd(10));
let mode='classic',role=null,peer=null,hostConn=null,room='',state=null,snap=null,selected=[],conns=new Map();
function rnd(n=6){const c='ABCDEFGHJKLMNPQRSTUVWXYZ23456789',a=new Uint32Array(n);crypto.getRandomValues(a);return [...a].map(x=>c[x%c.length]).join('')}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function show(x){['home','lobby','game'].forEach(y=>$('#'+y).classList.toggle('hide',x!==y))}
function note(el,msg,type=''){el.textContent=msg;el.className='notice'+(type?' '+type:'');el.classList.remove('hide')}
function clear(el){el.classList.add('hide')}
function name(){return ($('#name').value.trim()||localStorage.rumixName||'Jogador').slice(0,18)}
function saveName(){localStorage.rumixName=name()}
function label(m){return MODES[m]||m}
function toast(m){try{AndroidApp.toast(m)}catch(e){}}
$$('.mode').forEach(e=>e.onclick=()=>{$$('.mode').forEach(x=>x.classList.remove('active'));e.classList.add('active');mode=e.dataset.mode});
$('#name').value=localStorage.rumixName||'';
$('#joinCode').oninput=e=>e.target.value=e.target.value.toUpperCase().replace(/[^A-Z0-9]/g,'');
$('#createBtn').onclick=createRoom;$('#joinBtn').onclick=()=>joinRoom($('#joinCode').value.trim().toUpperCase());
$('#shareBtn').onclick=share;$('#copyBtn').onclick=async()=>{try{await navigator.clipboard.writeText(room);toast('Código copiado')}catch(e){note($('#lobbyNotice'),'Código: '+room,'ok')}};
$('#startBtn').onclick=()=>action({type:'START'});$('#leaveBtn').onclick=()=>location.reload();
$('#playBtn').onclick=()=>action({type:'PLAY',ids:[...selected]});$('#undoBtn').onclick=()=>action({type:'UNDO'});$('#endBtn').onclick=()=>action({type:'END'});$('#drawBtn').onclick=()=>action({type:'DRAW'});
window.RumiMix={openInvite(c){show('home');$('#joinCode').value=String(c||'').toUpperCase();note($('#homeNotice'),'Convite recebido para a sala '+$('#joinCode').value+'. Digite seu nome e toque em Entrar na sala.','ok')}};
const q=new URLSearchParams(location.search);if(q.get('room'))window.RumiMix.openInvite(q.get('room'));
function peerErr(p,el){p.on('error',e=>{const m=e.type==='peer-unavailable'?'Sala não encontrada ou anfitrião desconectado.':e.type==='network'?'Falha de rede. Confira a internet.':'Conexão: '+(e.type||e.message);note(el,m,'error')})}
function createRoom(){if(typeof Peer==='undefined'){note($('#homeNotice'),'Serviço multiplayer indisponível. Confira a internet.','error');return}saveName();room=rnd(6);role='host';peer=new Peer('rumix-'+room.toLowerCase()+'-host',{debug:1});peerErr(peer,$('#homeNotice'));peer.on('open',()=>{state=fresh();state.players.push({id,name:name(),hand:[],opened:false,connected:true});showLobby();broadcast()});peer.on('connection',incoming)}
function joinRoom(c){if(!/^[A-Z0-9]{4,8}$/.test(c)){note($('#homeNotice'),'Digite um código de sala válido.','error');return}if(typeof Peer==='undefined'){note($('#homeNotice'),'Serviço multiplayer indisponível. Confira a internet.','error');return}saveName();room=c;role='client';peer=new Peer(undefined,{debug:1});peerErr(peer,$('#homeNotice'));peer.on('open',()=>{hostConn=peer.connect('rumix-'+room.toLowerCase()+'-host',{reliable:true});bindHost(hostConn)})}
function bindHost(c){c.on('open',()=>{c.send({type:'JOIN',id,name:name()});showLobby();note($('#lobbyNotice'),'Conectado à sala.','ok')});c.on('data',m=>{if(m.type==='SNAP'){snap=m.data;room=snap.code;render()}else if(m.type==='REJECT')note($('#lobbyNotice'),m.message,'error')});c.on('close',()=>note($('#game').classList.contains('hide')?$('#lobbyNotice'):$('#gameNotice'),'Conexão com o anfitrião foi encerrada.','error'))}
function incoming(c){c.on('data',m=>{if(m.type==='JOIN'){if(state.status!=='lobby'){c.send({type:'REJECT',message:'A partida já começou.'});return}let p=state.players.find(x=>x.id===m.id);if(!p&&state.players.length>=8){c.send({type:'REJECT',message:'Sala cheia (8 jogadores).'});return}if(!p){p={id:m.id,name:String(m.name||'Jogador').slice(0,18),hand:[],opened:false,connected:true};state.players.push(p)}else{p.connected=true;p.name=String(m.name||p.name).slice(0,18)}conns.set(m.id,c);c.pid=m.id;c.on('close',()=>{let x=state&&state.players.find(z=>z.id===c.pid);if(x){x.connected=false;broadcast()}});log(p.name+' entrou na sala.');broadcast()}else if(m.type==='ACTION'&&c.pid)handle(c.pid,m.a)})}
function fresh(){return{code:room,mode,status:'lobby',hostId:id,players:[],deck:[],table:[],draft:{playerId:null,groups:[]},turn:0,winner:null,log:[],seq:1}}
function tid(){return't'+state.seq++}function tile(type,value,color=null,joker=false){return{id:tid(),type,value,color,joker}}
function shuffle(a){for(let i=a.length-1;i>0;i--){let j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function deck(m,n){let a=[];if(m==='classic'||m==='mixed'){let copies=n<=4?2:n<=6?3:4;for(let k=0;k<copies;k++)for(const c of COLORS)for(let v=1;v<=13;v++)a.push(tile('number',v,c));for(let j=0;j<Math.max(2,Math.ceil(copies/2)*2);j++)a.push(tile('joker','★','joker',true))}if(m==='words'||m==='mixed'){const f={A:14,B:3,C:5,D:6,E:12,F:3,G:3,H:2,I:10,J:2,K:1,L:5,M:6,N:5,O:11,P:4,Q:1,R:7,S:8,T:5,U:5,V:2,W:1,X:1,Y:1,Z:1},mul=m==='words'?(n<=4?1:2):1;for(let k=0;k<mul;k++)for(const [l,v] of Object.entries(f))for(let i=0;i<v;i++)a.push(tile('letter',l));if(m==='words')for(let j=0;j<2;j++)a.push(tile('joker','★','joker',true))}return shuffle(a)}
function cur(){return state.players[state.turn%state.players.length]}function log(m){state.log.unshift({m,t:Date.now()});state.log=state.log.slice(0,30)}
function showLobby(){show('lobby');$('#roomCode').textContent=room;$('#startBtn').classList.toggle('hide',role!=='host');renderLobby()}
function renderLobby(){const s=role==='host'?state:snap;if(!s)return;$('#roomCode').textContent=s.code;$('#lobbyMode').textContent=label(s.mode);$('#playerCount').textContent=s.players.length+'/8';$('#lobbyPlayers').innerHTML=s.players.map(p=>`<div class="player ${p.id===id?'me':''}"><b>${esc(p.name)}</b><div class="muted">${p.id===s.hostId?'👑 anfitrião':'jogador'}${p.connected===false?' • offline':''}</div></div>`).join('');if(role==='host')$('#startBtn').disabled=!state.players.length}
function share(){try{AndroidApp.shareInvite(room)}catch(e){note($('#lobbyNotice'),'Convite: rumix://join/'+room,'ok')}}
function action(a){clear($('#gameNotice'));if(role==='host')handle(id,a);else if(hostConn?.open)hostConn.send({type:'ACTION',a})}
function handle(pid,a){if(!state)return;if(a.type==='START'){if(pid!==state.hostId||state.status!=='lobby')return;state.deck=deck(state.mode,state.players.length);for(const p of state.players){p.hand=[];p.opened=false;for(let i=0;i<14&&state.deck.length;i++)p.hand.push(state.deck.pop())}state.status='playing';state.turn=0;state.draft={playerId:cur().id,groups:[]};log('Partida iniciada em '+label(state.mode)+'.');broadcast();return}if(state.status!=='playing')return;const p=cur();if(!p||p.id!==pid){err(pid,'Aguarde sua vez.');return}
if(a.type==='PLAY'){const ids=[...new Set(a.ids||[])];if(ids.length<3){err(pid,'Selecione pelo menos 3 peças.');return}const ts=ids.map(x=>p.hand.find(t=>t.id===x));if(ts.some(x=>!x)){err(pid,'Seleção inválida.');return}const v=valid(state.mode,ts);if(!v.ok){err(pid,v.msg);return}p.hand=p.hand.filter(t=>!ids.includes(t.id));state.draft.groups.push({id:'g'+Date.now()+Math.random(),tiles:ts,label:v.label,score:v.score});log(p.name+' montou '+v.label+'.');broadcast();return}
if(a.type==='UNDO'){if(!state.draft.groups.length){err(pid,'Não há jogadas para desfazer.');return}for(const g of state.draft.groups)p.hand.push(...g.tiles);state.draft.groups=[];broadcast();return}
if(a.type==='END'){if(!state.draft.groups.length){err(pid,'Baixe ao menos um grupo ou compre uma peça.');return}const total=state.draft.groups.reduce((s,g)=>s+g.score,0),min=state.mode==='classic'?30:state.mode==='words'?7:20;if(!p.opened&&total<min){for(const g of state.draft.groups)p.hand.push(...g.tiles);state.draft.groups=[];err(pid,'Primeira abertura precisa somar pelo menos '+min+' pontos.');broadcast();return}p.opened=true;state.table.push(...state.draft.groups);state.draft.groups=[];if(!p.hand.length){state.status='finished';state.winner=p.id;log('🏆 '+p.name+' venceu a partida!');broadcast();return}next();return}
if(a.type==='DRAW'){if(state.draft.groups.length){err(pid,'Desfaça ou finalize as peças baixadas antes de comprar.');return}if(state.deck.length)p.hand.push(state.deck.pop());log(p.name+' comprou uma peça.');next()}}
function next(){state.turn=(state.turn+1)%state.players.length;state.draft={playerId:cur().id,groups:[]};broadcast()}
function err(pid,m){if(pid===id&&role==='host')note($('#gameNotice'),m,'error');else{const c=conns.get(pid);if(c?.open)c.send({type:'SNAP',data:{...shot(pid),error:m}})}}
function valid(m,t){if(m==='classic')return nums(t);if(m==='words')return word(t);let a=nums(t);if(a.ok)return a;let b=word(t);if(b.ok)return b;let c=code(t);if(c.ok)return c;return{ok:false,msg:'No modo misto, forme grupo/sequência numérica, palavra ou código A-1-B-2-C-3.'}}
function nums(t){if(t.length<3||t.some(x=>!x.joker&&x.type!=='number'))return{ok:false,msg:'Grupo numérico inválido.'};const j=t.filter(x=>x.joker).length,n=t.filter(x=>!x.joker);if(!n.length)return{ok:false,msg:'Não vale só curinga.'};const same=n.every(x=>x.value===n[0].value)&&new Set(n.map(x=>x.color)).size===n.length&&t.length<=4;if(same)return{ok:true,label:'grupo '+n[0].value,score:t.reduce((s,x)=>s+(x.joker?n[0].value:x.value),0)};if(!n.every(x=>x.color===n[0].color))return{ok:false,msg:'Sequência precisa ser da mesma cor.'};const v=n.map(x=>+x.value).sort((a,b)=>a-b);if(new Set(v).size!==v.length)return{ok:false,msg:'Número repetido na sequência.'};let gaps=0;for(let i=1;i<v.length;i++)gaps+=v[i]-v[i-1]-1;if(gaps>j)return{ok:false,msg:'Faltam peças para completar a sequência.'};return{ok:true,label:'sequência '+n[0].color,score:n.reduce((s,x)=>s+x.value,0)+j*Math.round(n.reduce((s,x)=>s+x.value,0)/n.length)}}
function word(t){if(t.length<3||t.some(x=>!x.joker&&x.type!=='letter'))return{ok:false,msg:'Palavra precisa ter 3 ou mais letras.'};return{ok:true,label:'palavra '+t.map(x=>x.joker?'?':x.value).join(''),score:t.length}}
function code(t){if(t.length<6||t.some(x=>x.joker))return{ok:false,msg:'Código misto inválido.'};const start=t[0].type;if(!['letter','number'].includes(start))return{ok:false,msg:'Código inválido.'};for(let i=0;i<t.length;i++){const e=i%2===0?start:(start==='letter'?'number':'letter');if(t[i].type!==e)return{ok:false,msg:'Alterne letra e número.'}}const l=t.filter(x=>x.type==='letter').map(x=>ABC.indexOf(x.value)),n=t.filter(x=>x.type==='number').map(x=>+x.value);for(let i=1;i<l.length;i++)if(l[i]!==l[i-1]+1)return{ok:false,msg:'Letras fora de sequência.'};for(let i=1;i<n.length;i++)if(n[i]!==n[i-1]+1)return{ok:false,msg:'Números fora de sequência.'};return{ok:true,label:'código misto',score:n.reduce((a,b)=>a+b,0)+l.length*2}}
function shot(pid){const me=state.players.find(p=>p.id===pid);return{code:state.code,mode:state.mode,status:state.status,hostId:state.hostId,players:state.players.map(p=>({id:p.id,name:p.name,count:p.hand.length,opened:p.opened,connected:p.connected})),myHand:me?me.hand:[],table:state.table,draft:state.draft,turn:state.turn,deckCount:state.deck.length,winner:state.winner,log:state.log}}
function broadcast(){if(role!=='host'||!state)return;snap=shot(id);render();for(const [pid,c] of conns)if(c.open)c.send({type:'SNAP',data:shot(pid)})}
function render(){const s=role==='host'?shot(id):snap;if(!s)return;if(s.error){note($('#gameNotice'),s.error,'error');delete s.error}if(s.status==='lobby'){show('lobby');renderLobby();return}show('game');selected=selected.filter(x=>(s.myHand||[]).some(t=>t.id===x));const c=s.players[s.turn%s.players.length],w=s.players.find(p=>p.id===s.winner);$('#turnText').textContent=s.status==='finished'?(w?'🏆 '+w.name+' venceu!':'Partida encerrada'):(c?.id===id?'🟡 Sua vez':'Vez de '+(c?.name||'...'));$('#gameMeta').textContent=label(s.mode)+' • Sala '+s.code;$('#deckCount').textContent=s.deckCount;$('#gamePlayers').innerHTML=s.players.map((p,i)=>`<div class="player ${i===s.turn&&s.status==='playing'?'turn':''} ${p.id===id?'me':''}"><b>${esc(p.name)}</b><div>${p.count} peças ${p.opened?'• aberto':''}</div></div>`).join('');const gs=[...(s.table||[]),...((s.draft&&s.draft.groups)||[]).map(g=>({...g,draft:true}))];$('#table').innerHTML=gs.length?gs.map(g=>`<div class="group ${g.draft?'draft':''}">${g.tiles.map(tileHtml).join('')}</div>`).join(''):'<div class="muted">A mesa ainda está vazia.</div>';$('#rack').innerHTML=(s.myHand||[]).map(t=>tileHtml(t,true)).join('');$$('#rack .tile').forEach(e=>e.onclick=()=>toggle(e.dataset.id));$('#log').innerHTML=(s.log||[]).map(x=>`<div>${esc(x.m)}</div>`).join('');const mine=s.status==='playing'&&c?.id===id;['playBtn','undoBtn','endBtn','drawBtn'].forEach(x=>$('#'+x).disabled=!mine)}
function tileHtml(t,r=false){const cls='tile '+(t.type==='letter'?'letter ':'')+(t.joker?'joker ':'')+(r&&selected.includes(t.id)?'selected':'');return`<div class="${cls}" data-id="${esc(t.id)}" data-color="${esc(t.color||'')}"><span>${esc(t.value)}</span><small>${t.joker?'CURINGA':t.type==='number'?(t.color||''):'LETRA'}</small></div>`}
function toggle(x){const i=selected.indexOf(x);i>=0?selected.splice(i,1):selected.push(x);render()}
})();
